#!/usr/bin/env python3
"""Scaffold a colocated Vitest repro spec that mounts a real stimulus
component with a reconstructed provenanceState, so an engineer starts from
"here is the exact state that reproduced the bug" instead of prose steps.

Follows this repo's existing unit-test pattern (see
src/components/audioAnalysis/TaskProvenanceNodes.spec.tsx,
src/store/hooks/useNextStep.spec.tsx): `renderToStaticMarkup` from
'react-dom/server', no jsdom / @testing-library — this repo has neither
installed, and per AGENTS.md new libraries need approval before adding.
This means the generated spec can only assert on what the component renders
synchronously from props (parameters + provenanceState) — NOT on effects
that require a real DOM (e.g. a d3 draw-to-canvas useEffect). The scaffold
says so explicitly and leaves the actual assertion as a TODO — this script
reproduces state, it does not guess what "correct" looks like.

Never runs itself, never overwrites an existing spec file without --force.

Usage:
  python generate_repro_spec.py <studyName>/config.json <componentInstanceName> \\
      <reconstructed_state.json> --repo-root . [--force]

Writes: src/public/<studyName>/assets/<ComponentFile>.repro.spec.tsx
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def resolve_component(config: dict, instance_name: str) -> dict:
    """Merge baseComponent + instance overrides, same rule as
    src/utils/handleComponentInheritance.ts."""
    components = config.get("components", {})
    if instance_name not in components:
        sys.exit(f"component instance {instance_name!r} not found in config.components")
    instance = components[instance_name]
    base_name = instance.get("baseComponent")
    merged = dict(config.get("baseComponents", {}).get(base_name, {})) if base_name else {}
    merged.update(instance)
    return merged


def default_export_name(src_path: Path) -> str:
    """Best-effort: read the component's default export name from `export
    default function X` / `export default X;` — falls back to file stem."""
    text = src_path.read_text()
    m = re.search(r"export default function (\w+)", text)
    if m:
        return m.group(1)
    m = re.search(r"export default (\w+)", text)
    if m:
        return m.group(1)
    return src_path.stem


def render_spec(
    component_name: str,
    relative_import_path: str,
    parameters: dict,
    reconstructed_state: dict,
    timing_note: str,
) -> str:
    params_json = json.dumps(parameters, indent=2)
    state_json = json.dumps(reconstructed_state, indent=2)
    return f"""import {{ renderToStaticMarkup }} from 'react-dom/server';
import {{ MantineProvider }} from '@mantine/core';
import {{ describe, expect, test, vi }} from 'vitest';
import {component_name} from '{relative_import_path}';

// Auto-generated by provenance-rehydration/scripts/generate_repro_spec.py.
// Reconstructed from a flagged moment in a review/usability recording — the
// state below is the EXACT trrack-derived application state at that moment,
// not a hand-written guess. Timing caveat: {timing_note}
//
// This only asserts on what the component renders synchronously from props
// (no jsdom/@testing-library in this repo, so useEffect-driven DOM drawing —
// e.g. d3 canvas rendering — will not run here). Add the real assertion for
// the bug below; this scaffold only reproduces the state.
//
// If this component (or anything it imports) uses @trrack/core, running this
// spec requires `test.server.deps.inline: ['@reduxjs/toolkit', '@trrack/core']`
// in vite.config.ts — @trrack/core's ESM build re-exports named imports from
// @reduxjs/toolkit's CJS build, which Vitest's default externalization can't
// resolve. See .github/skills/provenance-rehydration/references/rehydration-guide.md.

const parameters = {params_json};

const reconstructedProvenanceState = {state_json};

describe('{component_name} repro', () => {{
  test('renders with the reconstructed provenance state (TODO: assert the actual bug)', () => {{
    const markup = renderToStaticMarkup(
      <MantineProvider>
        <{component_name}
          parameters={{parameters}}
          provenanceState={{reconstructedProvenanceState}}
          setAnswer={{vi.fn()}}
          setProvenance={{vi.fn()}}
        />
      </MantineProvider>,
    );

    // TODO: replace with an assertion describing the bug, e.g.:
    // expect(markup).toContain('...');
    expect(markup).toBeTruthy();
  }});
}});
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("config_path", help="path to public/<studyName>/config.json")
    parser.add_argument("component_instance", help="the component instance name in config.components")
    parser.add_argument("state_json", help="path to a JSON file containing the reconstructed provenanceState")
    parser.add_argument("--timing-note", default="see the source finding/note for timing_confidence.")
    parser.add_argument("--repo-root", default=".", help="path to the repo root (default: cwd)")
    parser.add_argument("--force", action="store_true", help="overwrite an existing spec file")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    config = json.loads(Path(args.config_path).read_text())
    merged = resolve_component(config, args.component_instance)

    if merged.get("type") != "react-component":
        sys.exit(f"component instance {args.component_instance!r} is type={merged.get('type')!r}, not react-component — cannot scaffold a repro spec")

    rel_path = merged.get("path")
    if not rel_path:
        sys.exit(f"component instance {args.component_instance!r} has no 'path'")

    src_path = repo_root / "src" / "public" / rel_path
    if not src_path.is_file():
        sys.exit(f"component source not found: {src_path}")

    component_name = default_export_name(src_path)
    reconstructed_state = json.loads(Path(args.state_json).read_text())
    parameters = merged.get("parameters", {})

    spec_path = src_path.with_suffix("").with_name(src_path.stem + ".repro.spec.tsx")
    if spec_path.exists() and not args.force:
        sys.exit(f"{spec_path} already exists — pass --force to overwrite")

    spec = render_spec(
        component_name=component_name,
        relative_import_path=f"./{src_path.stem}",
        parameters=parameters,
        reconstructed_state=reconstructed_state,
        timing_note=args.timing_note,
    )
    spec_path.write_text(spec)
    print(f"wrote {spec_path.relative_to(repo_root)}")
    print("Run with: yarn unittest " + str(spec_path.relative_to(repo_root)))


if __name__ == "__main__":
    main()
